// eslint-disable-next-line capitalized-comments
/*
 * moleculer-db-mikroorm-adapter
 * Copyright (c) 2023 TyrSolutions (https://github.com/Tyrsolution/moleculer-db-mikroorm-adapter)
 * MIT Licensed
 */

'use strict';
import 'reflect-metadata';
import MikroORMDbAdapter from './adapter';
import {
	MikroORMConnection,
	EntityManager,
	EntityRepository,
	MikroORMConnectionOptions,
	OptionsBS,
	OptionsMongo,
	OptionsMYSQL,
	OptionsMaria,
	OptionsPost,
	OptionsSqlite,
	Services,
	ormMap,
	initORM,
	BSMikroORM,
	MongoMikroORM,
	MYSQLMikroORM,
	MariaMicroORM,
	PostMikroORM,
	SqliteMiroOrm,
	BSEntityManager,
	MongoEntityManager,
	MYSQLEntityManager,
	MariaEntityManager,
	PostEntityManager,
	SqliteEntityManager,
	BSEntityRepository,
	MongoEntityRepository,
	MYSQLEntityRepository,
	MariaEntityRepository,
	PostEntityRepository,
	SqliteEntityRepository,
	defineBSConfig,
	defineMongoConfig,
	defineMYSQLConfig,
	defineMariaConfig,
	definePostConfig,
	defineSqliteConfig,
} from './adapter/connectionManager/connection';
export {
	MikroORMConnection,
	EntityManager,
	EntityRepository,
	MikroORMConnectionOptions,
	OptionsBS,
	OptionsMongo,
	OptionsMYSQL,
	OptionsMaria,
	OptionsPost,
	OptionsSqlite,
	Services,
	ormMap,
	initORM,
	BSMikroORM,
	MongoMikroORM,
	MYSQLMikroORM,
	MariaMicroORM,
	PostMikroORM,
	SqliteMiroOrm,
	BSEntityManager,
	MongoEntityManager,
	MYSQLEntityManager,
	MariaEntityManager,
	PostEntityManager,
	SqliteEntityManager,
	BSEntityRepository,
	MongoEntityRepository,
	MYSQLEntityRepository,
	MariaEntityRepository,
	PostEntityRepository,
	SqliteEntityRepository,
	defineBSConfig,
	defineMongoConfig,
	defineMYSQLConfig,
	defineMariaConfig,
	definePostConfig,
	defineSqliteConfig,
	MikroORMDbAdapter as default,
};
